### ISSUE TITLE
EA: Implement the External Adapter:

### ISSUE THREAD

**Issue by stoqnkpL** [LimeChain/external-initiator#6]
- runs as a standalone server
- receives requests from the Chainlink Node with some API call result and a parameter specifying the Topic ID where we need to write the result to Hedera.
- Writes to Hedera Topic and returns a successful response to the Chainlink Node.
- Read: https://github.com/smartcontractkit/chainlink/wiki/External-Adapters
- use these two repos as a starting point:
 https://github.com/smartcontractkit/external-adapters-js
 https://github.com/Conflux-Network-Global/conflux-network-adapter

**Comment by Petyo-Lukanov** [comment]
This issue is covered in PR - https://github.com/LimeChain/external-adapter/pull/1
